services:
  - type: web
    name: buzz-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run prisma:generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
