import { StyleSheet } from "react-native";

export const adminStyles = StyleSheet.create({
  passwordContainer: {
    flex: 1,
    backgroundColor: "#000000",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  passwordCard: {
    backgroundColor: "rgba(20,20,25,0.6)",
    borderRadius: 24,
    padding: 32,
    alignItems: "center",
    width: "100%",
    maxWidth: 360,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  passwordTitle: {
    fontFamily: "Outfit_700Bold",
    fontSize: 24,
    color: "#FFFFFF",
    marginTop: 16,
  },
  passwordSubtitle: {
    fontFamily: "Outfit_400Regular",
    fontSize: 14,
    color: "#8A8A93",
    marginTop: 4,
    marginBottom: 24,
  },
  errorText: {
    fontFamily: "Outfit_500Medium",
    color: "#FF453A",
    fontSize: 13,
    marginBottom: 12,
  },
  unlockBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E99B16",
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 16,
    marginTop: 8,
  },
  unlockBtnText: {
    fontFamily: "Outfit_700Bold",
    color: "#000000",
    fontSize: 16,
    marginLeft: 8,
  },

  container: { flex: 1, backgroundColor: "#000000" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 54,
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: "rgba(5,5,8,0.8)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  headerTitle: {
    flex: 1,
    fontFamily: "Outfit_700Bold",
    fontSize: 24,
    color: "#FFFFFF",
    marginLeft: 16,
  },

  announcementSection: {
    backgroundColor: "rgba(233,155,22,0.1)",
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(233,155,22,0.3)",
  },
  announcementLabel: {
    fontFamily: "Outfit_700Bold",
    fontSize: 14,
    color: "#E99B16",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  announcementRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  announcementActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 12,
    gap: 12,
  },
  saveAnnouncementBtn: {
    backgroundColor: "#E99B16",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  saveAnnouncementText: {
    fontFamily: "Outfit_700Bold",
    color: "#000",
    fontSize: 13,
  },
  clearAnnouncementBtn: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  clearAnnouncementText: {
    fontFamily: "Outfit_600SemiBold",
    color: "#8A8A93",
    fontSize: 13,
  },
  currentAnnouncement: {
    fontFamily: "Outfit_400Regular",
    fontSize: 13,
    color: "#8A8A93",
    marginTop: 8,
    fontStyle: "italic",
  },

  commentBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  commentBadgeText: {
    fontFamily: "Outfit_500Medium",
    fontSize: 13,
    color: "#FFFFFF",
    marginLeft: 8,
    flex: 1,
  },

  tabs: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 12,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
  },
  tabActive: { backgroundColor: "#E99B16" },
  tabText: {
    fontFamily: "Outfit_600SemiBold",
    fontSize: 14,
    color: "#8A8A93",
    marginLeft: 6,
  },
  tabTextActive: { color: "#000000" },

  fab: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: "#E99B16",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 24,
    marginHorizontal: 20,
    marginVertical: 12,
    shadowColor: "#E99B16",
    shadowOpacity: 0.4,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  fabText: {
    fontFamily: "Outfit_700Bold",
    color: "#000",
    fontSize: 15,
    marginLeft: 8,
  },

  card: {
    backgroundColor: "rgba(20,20,25,0.5)",
    marginHorizontal: 20,
    marginBottom: 16,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  cardHeader: { flexDirection: "row", alignItems: "flex-start" },
  cardTitle: { fontFamily: "Outfit_700Bold", fontSize: 20, color: "#FFFFFF" },
  cardSub: { fontFamily: "Outfit_500Medium", fontSize: 14, color: "#E99B16", marginTop: 4 },
  cardMeta: { fontFamily: "Outfit_400Regular", fontSize: 13, color: "#8A8A93", marginTop: 6 },
  cardActions: { flexDirection: "row", gap: 12 },
  iconBtn: { padding: 8, backgroundColor: "rgba(255,255,255,0.05)", borderRadius: 12 },

  stopsSection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  stopsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  stopsTitle: { fontFamily: "Outfit_700Bold", fontSize: 14, color: "#8A8A93", textTransform: "uppercase", letterSpacing: 1 },
  addStopBtn: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(233,155,22,0.1)", paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  addStopText: { fontFamily: "Outfit_600SemiBold", fontSize: 12, color: "#E99B16", marginLeft: 4 },
  stopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: 12,
    borderRadius: 10,
    marginTop: 6,
  },
  stopName: { fontFamily: "Outfit_500Medium", fontSize: 15, color: "#FFFFFF", flex: 1 },
  stopCoords: { fontFamily: "Courier", fontSize: 12, color: "#8A8A93" },

  driverBadges: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  badge: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginRight: 8,
    marginBottom: 8,
  },
  badgeInactive: { backgroundColor: "rgba(255,69,58,0.1)", borderWidth: 1, borderColor: "rgba(255,69,58,0.3)" },
  badgeText: { fontFamily: "Outfit_500Medium", fontSize: 12, color: "#FFFFFF" },

  statusText: { fontFamily: "Outfit_600SemiBold", fontSize: 14, marginTop: 6, letterSpacing: 1 },
  active: { color: "#32D74B" },
  inactive: { color: "#FF453A" },

  emptyText: {
    fontFamily: "Outfit_400Regular",
    textAlign: "center",
    color: "#8A8A93",
    marginTop: 40,
    fontSize: 15,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    backgroundColor: "#111116",
    width: "90%",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  modalTitle: {
    fontFamily: "Outfit_700Bold",
    fontSize: 22,
    color: "#FFFFFF",
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: 14,
    padding: 16,
    fontSize: 15,
    fontFamily: "Outfit_400Regular",
    color: "#FFFFFF",
    marginBottom: 16,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  inputLabel: { fontFamily: "Outfit_500Medium", fontSize: 13, color: "#8A8A93", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 12,
  },
  modalBtn: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 14,
  },
  cancelBtn: { backgroundColor: "rgba(255,255,255,0.1)" },
  cancelBtnText: { fontFamily: "Outfit_600SemiBold", color: "#FFFFFF" },
  saveBtn: { backgroundColor: "#E99B16" },
  saveBtnText: { fontFamily: "Outfit_700Bold", color: "#000" },

  busPicker: { marginBottom: 16, maxHeight: 50 },
  busPickerItem: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    marginRight: 12,
  },
  busPickerItemActive: { backgroundColor: "#E99B16", borderColor: "#E99B16" },
  busPickerText: { fontFamily: "Outfit_600SemiBold", fontSize: 14, color: "#8A8A93" },
  busPickerTextActive: { color: "#000000" },

  activeToggle: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: 12,
    borderRadius: 12,
  },
});
